# Site settings
title: "주노의 블로그"
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site

# User settings
username: rainhelper
user_description: ""
email: rainhelper@gmail.com
facebook: rainhelper
linkedin: rainhelper
github:  rainhelper
#disqus_username:  rainhelper

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
